/**
 * Checkout Types
 *
 * Types for payment checkout operations (Stripe and Paytrail)
 */

// =============================================================================
// Request Types
// =============================================================================

/**
 * Customer data required for checkout
 */
export interface CheckoutCustomerData {
  /** Customer's first name */
  first_name: string;
  /** Customer's last name */
  last_name: string;
  /** Customer's email address */
  email: string;
  /** Street address */
  address: string;
  /** Postal code (5 digits for Finland) */
  postal_code: string;
  /** City name */
  city: string;
  /** Phone number */
  phone: string;
}

/**
 * Shipment method selection for checkout
 */
export interface CheckoutShipmentMethod {
  /** ID of the selected shipment method */
  shipmentMethodId: string;
  /** ID of pickup point (for pickup delivery methods) */
  pickupId: string | null;
  /** Shipit service ID (for Shipit pickup points) */
  serviceId: string | null;
}

/**
 * Ticket holder name for requiresHolder tickets
 */
export interface TicketHolderData {
  /** Holder's first name */
  firstName: string;
  /** Holder's last name */
  lastName: string;
}

/**
 * Parameters for creating a checkout session
 */
export interface CheckoutParams {
  /** Customer information */
  customerData: CheckoutCustomerData;
  /** Selected shipment method */
  shipmentMethod: CheckoutShipmentMethod | null;
  /** Unique order ID (generated by caller) */
  orderId: string;
  /** URL to redirect on successful payment */
  successUrl: string;
  /** URL to redirect on cancelled payment */
  cancelUrl: string;
  /** Ticket holder names keyed by product ID, one entry per ticket quantity */
  ticketHolders?: Record<string, TicketHolderData[]>;
}

// =============================================================================
// Response Types
// =============================================================================

/**
 * Response from Stripe checkout
 */
export interface StripeCheckoutResponse {
  /** URL to redirect user to Stripe checkout page */
  url: string;
}

/**
 * Response from PayPal checkout
 */
export interface PayPalCheckoutResponse {
  /** URL to redirect the buyer to PayPal's approval page */
  url: string;
  /** PayPal order id (Orders v2) — useful for support and reconciliation */
  paypalOrderId: string;
}

/**
 * Payment provider from Paytrail
 */
export interface PaytrailProvider {
  /** Form submission URL for this provider */
  url: string;
  /** Provider icon URL */
  icon: string;
  /** Provider SVG icon */
  svg: string;
  /** Provider name (e.g., "Nordea", "OP") */
  name: string;
  /** Provider group (e.g., "bank", "mobile", "creditcard") */
  group: string;
  /** Provider ID */
  id: string;
  /** Form parameters to submit to provider */
  parameters: Array<{ name: string; value: string }>;
}

/**
 * Payment method group from Paytrail
 */
export interface PaytrailGroup {
  /** Group ID (e.g., "bank", "mobile", "creditcard") */
  id: string;
  /** Group name */
  name: string;
  /** Group icon URL */
  icon: string;
  /** Group SVG icon */
  svg: string;
}

/**
 * Response from Paytrail checkout
 */
export interface PaytrailCheckoutResponse {
  /** Paytrail transaction ID */
  transactionId: string;
  /** Direct payment URL */
  href: string;
  /** Payment reference */
  reference: string;
  /** Terms and conditions URL */
  terms: string;
  /** Payment method groups */
  groups: PaytrailGroup[];
  /** Available payment providers */
  providers: PaytrailProvider[];
  /** Custom providers (if configured) */
  customProviders: Record<string, unknown>;
}

// =============================================================================
// Error Types
// =============================================================================

/**
 * Checkout error codes
 */
export type CheckoutErrorCode =
  | "EMPTY_CART"
  | "PRODUCT_NOT_FOUND"
  | "VARIATION_NOT_FOUND"
  | "INSUFFICIENT_INVENTORY"
  | "STORE_SETTINGS_NOT_FOUND"
  | "PAYMENT_FAILED";

/**
 * Error details for checkout failures
 */
export interface CheckoutErrorDetails {
  /** ID of the problematic product */
  productId?: string;
  /** ID of the problematic variation */
  variationId?: string;
  /** Available quantity (for inventory errors) */
  availableQuantity?: number;
  /** Requested quantity (for inventory errors) */
  requestedQuantity?: number;
  /** Additional error details */
  [key: string]: unknown;
}
